-- Script para criar o banco de dados e as tabelas necessárias.

CREATE DATABASE IF NOT EXISTS `openlibraryhub`;

USE `openlibraryhub`;

DROP TABLE IF EXISTS `livros`;

CREATE TABLE IF NOT EXISTS `livros` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `titulo` VARCHAR(255) NOT NULL,
    `autor` VARCHAR(255) NOT NULL,
    `secao` VARCHAR(255) NOT NULL,
    `paginas` BIGINT UNSIGNED UNSIGNED NOT NULL,
    `ano` BIGINT UNSIGNED UNSIGNED NOT NULL,
    `estoque` BIGINT UNSIGNED UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS `emprestimos`;
DROP TABLE IF EXISTS `alunos`;
DROP TABLE IF EXISTS `turmas`;

CREATE TABLE IF NOT EXISTS `turmas` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `nome` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `alunos` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `nome` VARCHAR(255) NOT NULL,
    `turma` BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (`turma`) REFERENCES `turmas`(`id`)
);

CREATE TABLE IF NOT EXISTS `emprestimos` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `aluno` BIGINT UNSIGNED NOT NULL,
    `livro` BIGINT UNSIGNED NOT NULL,
    `data_emprestimo` DATE NOT NULL,
    `data_devolucao` DATE NOT NULL,
    FOREIGN KEY (`aluno`) REFERENCES `alunos`(`id`),
    FOREIGN KEY (`livro`) REFERENCES `livros`(`id`)
);
