#!/bin/sh
set -e

SCRIPT_DIR=$(dirname -- "$BASH_SOURCE")

RED="\e[0;31m"
NC="\e[0m"

error() {
    echo -e "$RED* $1$NC"
}

if ! [ -d $SCRIPT_DIR/lib/mysql ]; then
    error "lib/mysql não encontrado"
    error "Execute './getlib' para baixar"
    exit 1
fi

if [ -f $SCRIPT_DIR/openlibraryhub ]; then
    LD_LIBRARY_PATH=$SCRIPT_DIR/lib/mysql/lib64:$LD_LIBRARY_PATH $SCRIPT_DIR/openlibraryhub
else
    error "Binário não encontrado..."
    error "Execute 'make' para compilar"
    exit 1
fi
